version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    container_name: laravel-app
    volumes:
      - app_data:/var/www/html
    networks:
      - lahmi

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - lahmi

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - db
      - app
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - lahmi

networks:
  lahmi:

volumes:
  dbdata:
  app_data:
